In [ ]:
import lsdb

cone = lsdb.ConeSearch(ra=0, dec=0, radius_arcsec=150_000.0)

gaia = lsdb.open_catalog('https://data.lsdb.io/hats/gaia_dr3', columns = ['ra', 'dec', 'phot_g_mean_mag'])#, search_filter=cone)

tess = lsdb.open_catalog('https://data.lsdb.io/hats/tess/tess_lightcurve') #, columns = ['ra', 'dec',])

sdss = lsdb.open_catalog('https://data.lsdb.io/hats/sdss_dr7_spectra') #, columns = ['ra', 'dec', 'phot_g_mean_mag'])

In [5]:
gaia

lsdb Catalog gaia:
                         solution_id      designation       source_id    random_index        ref_epoch               ra        ra_error              dec       dec_error         parallax  parallax_error parallax_over_error              pm             pmra      pmra_error            pmdec     pmdec_error     ra_dec_corr ra_parallax_corr    ra_pmra_corr   ra_pmdec_corr dec_parallax_corr   dec_pmra_corr  dec_pmdec_corr parallax_pmra_corr parallax_pmdec_corr pmra_pmdec_corr astrometric_n_obs_al astrometric_n_obs_ac astrometric_n_good_obs_al astrometric_n_bad_obs_al astrometric_gof_al astrometric_chi2_al astrometric_excess_noise astrometric_excess_noise_sig astrometric_params_solved astrometric_primary_flag nu_eff_used_in_astrometry    pseudocolour pseudocolour_error ra_pseudocolour_corr dec_pseudocolour_corr parallax_pseudocolour_corr pmra_pseudocolour_corr pmdec_pseudocolour_corr astrometric_matched_transits visibility_periods_used astrometric_sigma5d_max matched_transits new_matched_transits matched_transits_removed ipd_gof_harmonic_amplitude ipd_gof_harmonic_phase ipd_frac_multi_peak ipd_frac_odd_win            ruwe scan_direction_strength_k1 scan_direction_strength_k2 scan_direction_strength_k3 scan_direction_strength_k4 scan_direction_mean_k1 scan_direction_mean_k2 scan_direction_mean_k3 scan_direction_mean_k4 duplicated_source    phot_g_n_obs phot_g_mean_flux phot_g_mean_flux_error phot_g_mean_flux_over_error phot_g_mean_mag   phot_bp_n_obs phot_bp_mean_flux phot_bp_mean_flux_error phot_bp_mean_flux_over_error phot_bp_mean_mag   phot_rp_n_obs phot_rp_mean_flux phot_rp_mean_flux_error phot_rp_mean_flux_over_error phot_rp_mean_mag phot_bp_rp_excess_factor phot_bp_n_contaminated_transits phot_bp_n_blended_transits phot_rp_n_contaminated_transits phot_rp_n_blended_transits phot_proc_mode           bp_rp            bp_g            g_rp radial_velocity radial_velocity_error rv_method_used  rv_nb_transits rv_nb_deblended_transits rv_visibility_periods_used rv_expected_sig_to_noise rv_renormalised_gof rv_chisq_pvalue rv_time_duration rv_amplitude_robust rv_template_teff rv_template_logg rv_template_fe_h rv_atm_param_origin          vbroad    vbroad_error vbroad_nb_transits        grvs_mag  grvs_mag_error grvs_mag_nb_transits rvs_spec_sig_to_noise phot_variable_flag                l                b          ecl_lon          ecl_lat in_qso_candidates in_galaxy_candidates non_single_star has_xp_continuous has_xp_sampled        has_rvs has_epoch_photometry   has_epoch_rv has_mcmc_gspphot   has_mcmc_msc in_andromeda_survey classprob_dsc_combmod_quasar classprob_dsc_combmod_galaxy classprob_dsc_combmod_star    teff_gspphot teff_gspphot_lower teff_gspphot_upper    logg_gspphot logg_gspphot_lower logg_gspphot_upper      mh_gspphot mh_gspphot_lower mh_gspphot_upper distance_gspphot distance_gspphot_lower distance_gspphot_upper   azero_gspphot azero_gspphot_lower azero_gspphot_upper      ag_gspphot ag_gspphot_lower ag_gspphot_upper ebpminrp_gspphot ebpminrp_gspphot_lower ebpminrp_gspphot_upper  libname_gspphot
npartitions=2016
Order: 2, Pixel: 0    int64[pyarrow]  string[pyarrow]  int64[pyarrow]  int64[pyarrow]  double[pyarrow]  double[pyarrow]  float[pyarrow]  double[pyarrow]  float[pyarrow]  double[pyarrow]  float[pyarrow]      float[pyarrow]  float[pyarrow]  double[pyarrow]  float[pyarrow]  double[pyarrow]  float[pyarrow]  float[pyarrow]   float[pyarrow]  float[pyarrow]  float[pyarrow]    float[pyarrow]  float[pyarrow]  float[pyarrow]     float[pyarrow]      float[pyarrow]  float[pyarrow]       int16[pyarrow]       int16[pyarrow]            int16[pyarrow]           int16[pyarrow]     float[pyarrow]      float[pyarrow]           float[pyarrow]               float[pyarrow]             int8[pyarrow]            bool[pyarrow]            float[pyarrow]  float[pyarrow]     float[pyarrow]       float[pyarrow]        float[pyarrow]             float[pyarrow]         float[pyarrow]          float[pyarrow]               int16[pyarrow]          int16[pyarrow]          float[pyarrow]   int16[pyarrow]       int16[pyarrow]           int16[pyarrow]             float[pyarrow]         float[pyarrow]       int8[pyarrow]    int8[pyarrow]  float[pyarrow]             float[pyarrow]             float[pyarrow]             float[pyarrow]             float[pyarrow]         float[pyarrow]         float[pyarrow]         float[pyarrow]         float[pyarrow]     bool[pyarrow]  int16[pyarrow]  double[pyarrow]         float[pyarrow]              float[pyarrow]  float[pyarrow]  int16[pyarrow]   double[pyarrow]          float[pyarrow]               float[pyarrow]   float[pyarrow]  int16[pyarrow]   double[pyarrow]          float[pyarrow]               float[pyarrow]   float[pyarrow]           float[pyarrow]                  int16[pyarrow]             int16[pyarrow]                  int16[pyarrow]             int16[pyarrow]  int8[pyarrow]  float[pyarrow]  float[pyarrow]  float[pyarrow]  float[pyarrow]        float[pyarrow]  int8[pyarrow]  int16[pyarrow]           int16[pyarrow]             int16[pyarrow]           float[pyarrow]      float[pyarrow]  float[pyarrow]   float[pyarrow]      float[pyarrow]   float[pyarrow]   float[pyarrow]   float[pyarrow]      int16[pyarrow]  float[pyarrow]  float[pyarrow]     int16[pyarrow]  float[pyarrow]  float[pyarrow]       int16[pyarrow]        float[pyarrow]    string[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]  double[pyarrow]     bool[pyarrow]        bool[pyarrow]  int16[pyarrow]     bool[pyarrow]  bool[pyarrow]  bool[pyarrow]        bool[pyarrow]  bool[pyarrow]    bool[pyarrow]  bool[pyarrow]       bool[pyarrow]               float[pyarrow]               float[pyarrow]             float[pyarrow]  float[pyarrow]     float[pyarrow]     float[pyarrow]  float[pyarrow]     float[pyarrow]     float[pyarrow]  float[pyarrow]   float[pyarrow]   float[pyarrow]   float[pyarrow]         float[pyarrow]         float[pyarrow]  float[pyarrow]      float[pyarrow]      float[pyarrow]  float[pyarrow]   float[pyarrow]   float[pyarrow]   float[pyarrow]         float[pyarrow]         float[pyarrow]  string[pyarrow]
...                              ...              ...             ...             ...              ...              ...             ...              ...             ...              ...             ...                 ...             ...              ...             ...              ...             ...             ...              ...             ...             ...               ...             ...             ...                ...                 ...             ...                  ...                  ...                       ...                      ...                ...                 ...                      ...                          ...                       ...                      ...                       ...             ...                ...                  ...                   ...                        ...                    ...                     ...                          ...                     ...                     ...              ...                  ...                      ...                        ...                    ...                 ...              ...             ...                        ...                        ...                        ...                        ...                    ...                    ...                    ...                    ...               ...             ...              ...                    ...                         ...             ...             ...               ...                     ...                          ...              ...             ...               ...                     ...                          ...              ...                      ...                             ...                        ...                             ...                        ...            ...             ...             ...             ...             ...                   ...            ...             ...                      ...                        ...                      ...                 ...             ...              ...                 ...              ...              ...              ...                 ...             ...             ...                ...             ...             ...                  ...                   ...                ...              ...              ...              ...              ...               ...                  ...             ...               ...            ...            ...                  ...            ...              ...            ...                 ...                          ...                          ...                        ...             ...                ...                ...             ...                ...                ...             ...              ...              ...              ...                    ...                    ...             ...                 ...                 ...             ...              ...              ...              ...                    ...                    ...              ...
Order: 3, Pixel: 766             ...              ...             ...             ...              ...              ...             ...              ...             ...              ...             ...                 ...             ...              ...             ...              ...             ...             ...              ...             ...             ...               ...             ...             ...                ...                 ...             ...                  ...                  ...                       ...                      ...                ...                 ...                      ...                          ...                       ...                      ...                       ...             ...                ...                  ...                   ...                        ...                    ...                     ...                          ...                     ...                     ...              ...                  ...                      ...                        ...                    ...                 ...              ...             ...                        ...                        ...                        ...                        ...                    ...                    ...                    ...                    ...               ...             ...              ...                    ...                         ...             ...             ...               ...                     ...                          ...              ...             ...               ...                     ...                          ...              ...                      ...                             ...                        ...                             ...                        ...            ...             ...             ...             ...             ...                   ...            ...             ...                      ...                        ...                      ...                 ...             ...              ...                 ...              ...              ...              ...                 ...             ...             ...                ...             ...             ...                  ...                   ...                ...              ...              ...              ...              ...               ...                  ...             ...               ...            ...            ...                  ...            ...              ...            ...                 ...                          ...                          ...                        ...             ...                ...                ...             ...                ...                ...             ...              ...              ...              ...                    ...                    ...             ...                 ...                 ...             ...              ...              ...              ...                    ...                    ...              ...
Order: 3, Pixel: 767             ...              ...             ...             ...              ...              ...             ...              ...             ...              ...             ...                 ...             ...              ...             ...              ...             ...             ...              ...             ...             ...               ...             ...             ...                ...                 ...             ...                  ...                  ...                       ...                      ...                ...                 ...                      ...                          ...                       ...                      ...                       ...             ...                ...                  ...                   ...                        ...                    ...                     ...                          ...                     ...                     ...              ...                  ...                      ...                        ...                    ...                 ...              ...             ...                        ...                        ...                        ...                        ...                    ...                    ...                    ...                    ...               ...             ...              ...                    ...                         ...             ...             ...               ...                     ...                          ...              ...             ...               ...                     ...                          ...              ...                      ...                             ...                        ...                             ...                        ...            ...             ...             ...             ...             ...                   ...            ...             ...                      ...                        ...                      ...                 ...             ...              ...                 ...              ...              ...              ...                 ...             ...             ...                ...             ...             ...                  ...                   ...                ...              ...              ...              ...              ...               ...                  ...             ...               ...            ...            ...                  ...            ...              ...            ...                 ...                          ...                          ...                        ...             ...                ...                ...             ...                ...                ...             ...              ...              ...              ...                    ...                    ...             ...                 ...                 ...             ...              ...              ...              ...                    ...                    ...              ...
152 out of 152 available columns in the catalog have been loaded lazily, meaning no data has been read, only the catalog schema
This catalog has an estimated size of 765.3 GB

In [7]:
gaia_query = gaia.query("phot_g_mean_mag < 20")

In [11]:
gaia_x_tess = gaia.crossmatch(tess, suffix_method='overlapping_columns')

In [28]:
gaia_mmu = gaia_x_tess.crossmatch(sdss)

/Users/drew/opt/miniconda3/envs/hyrax/lib/python3.13/site-packages/lsdb/catalog/catalog.py:410: FutureWarning: The default suffix behavior will change from applying suffixes to all columns to only applying suffixes to overlapping columns in a future release.To maintain the current behavior, explicitly set `suffix_method='all_columns'`. To change to the new behavior, set `suffix_method='overlapping_columns'`.
  warnings.warn(

In [ ]:
import pandas as pd
from lsdb.streams import CatalogStream, InfiniteStream

cat_stream = CatalogStream(gaia_mmu, partitions_per_chunk=2, shuffle=False)
# inf_stream = InfiniteStream(gaia_mmu, partitions_per_chunk=2, shuffle=False)

df = []

for i, chunk in enumerate(cat_stream):
    df.append(chunk)
    if i == 2:
        break

df = pd.concat(df, ignore_index=True)

In [30]:
df

    solution_id_gaia_x_tess_lightcurve designation_gaia_x_tess_lightcurve  \
0                  1636148068921376768       Gaia DR3 6913162042334862720
1                  1636148068921376768       Gaia DR3 6913165139007548032
2                  1636148068921376768       Gaia DR3 6913234133360925568
3                  1636148068921376768       Gaia DR3 6913377379111163264
4                  1636148068921376768       Gaia DR3 6913428089788776064
5                  1636148068921376768       Gaia DR3 6913544848475076992
6                  1636148068921376768       Gaia DR3 6913648404431277056
7                  1636148068921376768       Gaia DR3 6914363228723335296
8                  1636148068921376768       Gaia DR3 6917244151050758272
9                  1636148068921376768       Gaia DR3 6909407828600002688
10                 1636148068921376768       Gaia DR3 6910231946927487104
11                 1636148068921376768       Gaia DR3 6910231951220931968
12                 1636148068921376768       Gaia DR3 6910341691929801856
13                 1636148068921376768       Gaia DR3 6910475935427725824
14                 1636148068921376768       Gaia DR3 6910531598203174784
15                 1636148068921376768       Gaia DR3 6910712605305489024
16                 1636148068921376768       Gaia DR3 6910816513450124288
17                 1636148068921376768       Gaia DR3 6911173609915385216
18                 1636148068921376768       Gaia DR3 6911972405112364800
19                 1636148068921376768       Gaia DR3 6907274127503303552
20                 1636148068921376768       Gaia DR3 6907356625235015808
21                 1636148068921376768       Gaia DR3 6907356625234164992
22                 1636148068921376768       Gaia DR3 6907394936343369984
23                 1636148068921376768       Gaia DR3 6907659643768938368
24                 1636148068921376768       Gaia DR3 6908219737568396672
25                 1636148068921376768       Gaia DR3 6908398309423020544
26                 1636148068921376768       Gaia DR3 6908407066861225728

    source_id_gaia_x_tess_lightcurve  random_index_gaia_x_tess_lightcurve  \
0                6913162042334862720                             60289587
1                6913165139007548032                           1503967116
2                6913234133360925568                            282806257
3                6913377379111163264                           1311034966
4                6913428089788776064                            706524552
5                6913544848475076992                           1641491307
6                6913648404431277056                            747831166
7                6914363228723335296                           1437806393
8                6917244151050758272                           1773957357
9                6909407828600002688                           1248867277
10               6910231946927487104                            882230190
11               6910231951220931968                           1636599951
12               6910341691929801856                           1560708179
13               6910475935427725824                            945963246
14               6910531598203174784                           1108468347
15               6910712605305489024                            838562240
16               6910816513450124288                            539780873
17               6911173609915385216                            373696136
18               6911972405112364800                            867512591
19               6907274127503303552                            580444295
20               6907356625235015808                            494857824
21               6907356625234164992                             75850292
22               6907394936343369984                            513451959
23               6907659643768938368                            921919814
24               6908219737568396672                            669583630
25               6908398309423020544                           1383272727
26               6908407066861225728                           1412761293

    ref_epoch_gaia_x_tess_lightcurve  ra_gaia_x_tess_lightcurve  \
0                             2016.0                 312.074424
1                             2016.0                 312.127186
2                             2016.0                 313.126199
3                             2016.0                 311.130978
4                             2016.0                 311.678653
5                             2016.0                 311.853785
6                             2016.0                 313.816246
7                             2016.0                 311.203843
8                             2016.0                 315.671184
9                             2016.0                 315.932968
10                            2016.0                 314.846004
11                            2016.0                 314.846243
12                            2016.0                 314.811954
13                            2016.0                 315.461113
14                            2016.0                 314.737961
15                            2016.0                 314.876056
16                            2016.0                 318.122813
17                            2016.0                 317.367977
18                            2016.0                 316.127921
19                            2016.0                 310.577173
20                            2016.0                 310.322965
21                            2016.0                 310.322856
22                            2016.0                 310.728658
23                            2016.0                  308.82291
24                            2016.0                 310.098347
25                            2016.0                  309.58841
26                            2016.0                 309.217995

    ra_error_gaia_x_tess_lightcurve  dec_gaia_x_tess_lightcurve  \
0                          0.276699                     -6.1792
1                          6.300795                   -6.073101
2                          0.137376                   -5.792358
3                            0.2922                   -6.244482
4                           0.14966                   -5.638035
5                          0.074832                   -5.319693
6                          0.157538                   -5.311504
7                          0.044118                    -4.99134
8                          0.072249                   -0.735667
9                           0.12427                   -7.289169
10                         0.054719                   -6.869157
11                         0.534296                   -6.868765
12                         0.238359                   -6.205708
13                         0.170465                   -5.764211
14                         0.102147                   -6.088797
15                         0.107244                   -5.480333
16                         0.093664                   -6.681121
17                          0.08806                   -5.645354
18                           0.1723                   -5.569661
19                         0.102591                   -6.944034
20                         0.445664                   -6.479854
21                         0.131438                    -6.47973
22                         0.295079                   -6.063749
23                         0.209313                   -6.761124
24                          0.13564                   -5.687589
25                         0.106926                    -5.57028
26                         0.172609                   -5.579949

    dec_error_gaia_x_tess_lightcurve  parallax_gaia_x_tess_lightcurve  ...  \
0                           0.189929                         1.948898  ...
1                           3.061219                             <NA>  ...
2                           0.086725                         2.398428  ...
3                           0.195494                         4.018824  ...
4                           0.099875                          5.04465  ...
5                           0.043087                         5.564719  ...
6                           0.068373                         2.545308  ...
7                           0.026065                         0.485159  ...
8                           0.062931                         0.053577  ...
9                           0.092641                          2.77652  ...
10                          0.038259                         1.414884  ...
11                          0.344966                         4.140993  ...
12                          0.162061                         0.928616  ...
13                          0.128766                         1.899484  ...
14                          0.070279                         3.052778  ...
15                          0.079961                         0.707168  ...
16                          0.078385                         2.772321  ...
17                          0.076601                          2.11294  ...
18                          0.130412                         4.092812  ...
19                          0.057857                         0.609261  ...
20                          0.380951                         0.882875  ...
21                          0.092748                         0.409568  ...
22                          0.180776                         6.373763  ...
23                           0.12439                         2.083461  ...
24                          0.086155                         5.821448  ...
25                          0.073678                         5.002466  ...
26                          0.105593                         7.098025  ...

    PRIMTARGET_sdss_dr7_spectra  SECTARGET_sdss_dr7_spectra  \
0                             4                           0
1                            64                           0
2                     546832384                         512
3                   -2147418112                  1073741824
4                       1048580                           0
5                   -2146959360                  1073741824
6                     545259520                         512
7                   -2146435072                  1073741824
8                             2                           0
9                     546832384                         512
10                            4                           0
11                            4                           0
12                            4                           0
13                    546832384                         512
14                            5                           0
15                    545259520                         512
16                    537395200                         512
17                    536870912                         512
18                      9969668                           0
19                            1                           0
20                            5                           0
21                            5                           0
22                  -2147418112                  1073741824
23                    546832384                         512
24                      1048580                           0
25                    537919488                         512
26                            4                           0

    OFFSETID_sdss_dr7_spectra  SCI_EXPTIME_sdss_dr7_spectra  \
0                           1                           0.0
1                           1                           0.0
2                           1                           0.0
3                           1                           0.0
4                           1                           0.0
5                           1                           0.0
6                           1                           0.0
7                           1                           0.0
8                           1                           0.0
9                           1                           0.0
10                          1                           0.0
11                          1                           0.0
12                          1                           0.0
13                          1                           0.0
14                          1                           0.0
15                          1                           0.0
16                          1                           0.0
17                          1                           0.0
18                          1                           0.0
19                          1                           0.0
20                          1                           0.0
21                          1                           0.0
22                          1                           0.0
23                          1                           0.0
24                          1                           0.0
25                          1                           0.0
26                          1                           0.0

                           CALIBFLUX_sdss_dr7_spectra  \
0   [17.927525 17.503994 19.664799 20.58579  26.64...
1   [  2.6037397  15.027621   40.00187    70.6517 ...
2   [53.03103  47.51576  34.08334  26.11106  18.76...
3   [ 52.07479  97.93215 229.10873 439.0545  646.3...
4   [19.722343 28.244726 32.23214  33.05794  30.76...
5   [141.87553  158.64856  119.57518   94.254005  ...
6   [52.837708 49.921593 36.80825  28.10745  22.07...
7   [120.603905 173.47592  305.8463   395.67325  5...
8   [ 40.860867 124.76368  142.37653  147.39514  1...
9   [65.043106 56.653423 41.984467 31.73448  23.94...
10  [118.19128 131.52846 187.09775 258.33383 272.9...
11  [118.19128 131.52846 187.09775 258.33383 272.9...
12  [54.631565 42.474525 43.24111  52.278934 63.96...
13  [41.68435  32.867798 23.530516 17.049894 11.99...
14  [ 67.96715   77.18763   63.053368  75.15562  1...
15  [133.1855    82.04403   51.56461   37.269543  ...
16  [138.69012  126.10916   89.64322   69.31879   ...
17  [150.19455  109.8678    74.78981   56.103115  ...
18  [26.63461  38.79108  35.02853  28.103848 25.38...
19  [  2.145745  16.134512  67.45147  114.61827  1...
20  [ 22.851034  22.83597   40.693073  73.83041  1...
21  [ 22.851034  22.83597   40.693073  73.83041  1...
22  [ 7.1864185 10.736561  13.989764  15.328451  1...
23  [33.23023  27.473028 20.66592  15.782757 14.92...
24  [26.388752 37.90983  37.156673 33.51616  27.07...
25  [54.50205  51.237274 43.87407  37.0452   32.07...
26  [15.992918 23.70352  25.99867  27.347383 27.17...

                      CALIBFLUX_IVAR_sdss_dr7_spectra  \
0   [ 0.         14.834377   16.390009    7.258617...
1   [ 4.2883997  21.9479      0.          2.781611...
2   [1.0588753 4.7632575 7.0792713 7.3931637 0.689...
3   [1.3025019  0.79878706 0.24453123 0.00280554 0...
4   [ 3.4011776 15.740444   6.788516   7.0102673  ...
5   [0.27625737 0.38101876 1.1288292  1.0242761  0...
6   [1.0755682 3.8183594 7.0363326 4.4018826 0.   ...
7   [0.24381486 0.43585843 0.10045107 0.06402094 0...
8   [1.5093267  0.21855707 0.53261274 0.45190978 0...
9   [0.56230694 2.8653948  6.226538   6.132509   0...
10  [0.18165068 0.45832062 0.23918103 0.11654206 0...
11  [0.18165068 0.45832062 0.23918103 0.11654206 0...
12  [1.0110018  4.5082445  5.3705134  2.9872398  0...
13  [ 1.4687421  7.27505   11.470818   9.171002   ...
14  [0.7287175  1.5478141  2.9011636  1.6998593  0...
15  [0.19339015 1.2245053  2.480209   2.916934   0...
16  [0.15544666 0.38890058 1.196968   0.7602479  0...
17  [0.12397097 0.5080921  1.245716   2.0099487  0...
18  [2.490346  4.7094026 6.0507684 5.4432626 0.515...
19  [2.923034   0.508155   0.61975914 0.27290294 0...
20  [2.9008043  8.970642   7.1033483  1.4941736  0...
21  [2.9008043  8.970642   7.1033483  1.4941736  0...
22  [ 6.6352806 37.48283   25.134346  14.538988   ...
23  [ 2.0699952   6.9166937  15.82851    10.392065...
24  [2.8463035 7.661527  7.881234  4.6138043 0.602...
25  [0.7210846 5.9371643 5.4304185 2.1995966 0.576...
26  [ 4.4135337  19.363453    7.0286417   6.100339...

    SFD_EBV_sdss_dr7_spectra  \
0                   0.063544
1                   0.057621
2                   0.074958
3                   0.049296
4                   0.065557
5                   0.056484
6                   0.062113
7                    0.05185
8                   0.068716
9                   0.091059
10                  0.061097
11                  0.061097
12                   0.04707
13                  0.056587
14                  0.045629
15                  0.046164
16                  0.094668
17                  0.103171
18                  0.073648
19                  0.037079
20                  0.049597
21                  0.049597
22                  0.050773
23                  0.040872
24                   0.05829
25                  0.060573
26                  0.050491

                             spectra_sdss_dr7_spectra  \
0   [{andmask: 83886080, flux: 8.690218, ivar: 0.0...
1   [{andmask: 83886080, flux: -1.113093, ivar: 0....
2   [{andmask: 16777216, flux: 35.211098, ivar: 0....
3   [{andmask: 67108864, flux: 34.789577, ivar: 0....
4   [{andmask: 16777216, flux: 17.768267, ivar: 0....
5   [{andmask: 16777216, flux: 123.759171, ivar: 0...
6   [{andmask: 16777216, flux: 38.682575, ivar: 0....
7   [{andmask: 16777216, flux: 71.967384, ivar: 0....
8   [{andmask: 16777216, flux: 70.137573, ivar: 0....
9   [{andmask: 83886080, flux: 52.21299, ivar: 0.0...
10  [{andmask: 16777216, flux: 89.155014, ivar: 0....
11  [{andmask: 16777216, flux: 89.155014, ivar: 0....
12  [{andmask: 16777216, flux: 18.620913, ivar: 0....
13  [{andmask: 16777216, flux: 36.166706, ivar: 0....
14  [{andmask: 16777216, flux: 51.57098, ivar: 0.0...
15  [{andmask: 16777216, flux: 79.308083, ivar: 0....
16  [{andmask: 16777216, flux: 108.12159, ivar: 0....
17  [{andmask: 16777216, flux: 98.080559, ivar: 0....
18  [{andmask: 16777216, flux: 18.550203, ivar: 0....
19  [{andmask: 16777216, flux: 9.929678, ivar: 0.0...
20  [{andmask: 16777216, flux: 15.52844, ivar: 0.0...
21  [{andmask: 16777216, flux: 15.52844, ivar: 0.0...
22  [{andmask: 16777216, flux: 5.733247, ivar: 0.0...
23  [{andmask: 16777216, flux: 16.422668, ivar: 0....
24  [{andmask: 16777216, flux: 28.131775, ivar: 0....
25  [{andmask: 16777216, flux: 45.577618, ivar: 0....
26  [{andmask: 16777216, flux: 17.022631, ivar: 0....

    __index_level_0___sdss_dr7_spectra  _dist_arcsec
0                                  126      0.345923
1                                  133      0.097553
2                                  619      0.062834
3                                  165      0.128692
4                                  441      0.306179
5                                  541      0.597253
6                                  443      0.366348
7                                  423       0.01695
8                                   51      0.103119
9                                  122      0.072263
10                                  63      0.899103
11                                  63      0.803055
12                                 598      0.079881
13                                 431      0.219009
14                                 591      0.260701
15                                 616      0.261816
16                                 557      0.289474
17                                 418      0.202011
18                                 546      0.194173
19                                  10      0.158897
20                                  46      0.429847
21                                  46       0.20277
22                                 269      0.037041
23                                 293      0.128517
24                                 516      0.209889

In [32]:
df.iloc[0]['spectra_sdss_dr7_spectra']

       andmask      flux      ivar     ormask   skyflux  wavedisp
0     83886080  8.690218  0.000000  219152384  0.000000  0.000000
1            0  8.688969  0.049828  201326592  9.343218  1.304895
...        ...       ...       ...        ...       ...       ...
3853  16777216  2.223426  0.000000   16777216  0.000000  0.000000
3854  16777216  2.223439  0.000000   16777216  0.000000  0.000000

[3855 rows x 6 columns]

In [33]:
df.iloc[0]['lightcurve_gaia_x_tess_lightcurve']

,time,pdcsap_flux,pdcsap_flux_err,sap_flux,sap_flux_err,quality
0,3506.552467,NaN,NaN,NaN,NaN,40
1,3506.553856,NaN,NaN,NaN,NaN,32
...,...,...,...,...,...,...
19172,3533.180543,14.365026,5.171197,32.465172,3.048639,0
19173,3533.181932,-2.629680,5.147275,22.412525,3.034535,0

In [34]:
df.iloc[0]['ra_gaia_x_tess_lightcurve']

312.0744243016191

In [35]:
df.iloc[0]['dec_gaia_x_tess_lightcurve']

-6.179200390609073

In [36]:
cat_iter = iter(cat_stream)
counter = 0

while True:
    try:
        chunk = next(cat_iter)
        print(f"Chunk {counter}: {len(chunk)} rows")
        counter += 1
        if counter == 2:
            break
    except StopIteration:
        break

Chunk 0: 9 rows
Chunk 1: 10 rows